### ISSUE TITLE
Errors after make

### ISSUE THREAD

**Issue by enogueiras** [gotoco/dummyfs#1]
Hi, I got the following errors after make

_utnso@ubuntu-server:~/workspace/dummyfs$ make
make -C /lib/modules/4.4.0-116-generic/build SUBDIRS=/home/utnso/workspace/dummyfs modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-116-generic'
  CC [M]  /home/utnso/workspace/dummyfs/dummyfs.o
/home/utnso/workspace/dummyfs/dummyfs.c:46:2: error: unknown field ‘iterate_shared’ specified in initializer
  .iterate_shared = dummy_readdir,
  ^
/home/utnso/workspace/dummyfs/dummyfs.c:46:20: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .iterate_shared = dummy_readdir,
                    ^
/home/utnso/workspace/dummyfs/dummyfs.c:46:20: note: (near initialization for ‘dummy_dir_ops.llseek’)
scripts/Makefile.build:258: recipe for target '/home/utnso/workspace/dummyfs/dummyfs.o' failed
make[2]: *** [/home/utnso/workspace/dummyfs/dummyfs.o] Error 1
Makefile:1423: recipe for target '_module_/home/utnso/workspace/dummyfs' failed
make[1]: *** [_module_/home/utnso/workspace/dummyfs] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-116-generic'
Makefile:16: recipe for target 'default' failed
make: *** [default] Error 2_
utnso@ubuntu-server:~/workspace/dummyfs$ 

Can you please check it?
Thanks!

**Comment by mmpg-x86** [comment]
Hello, thank you for the email!

The reason why you see this error is due to your kernel version. 
I am not 100% sure what is inside Canonical `4.4.0-116-generic`, however it seems that is an older version of `file_operations` interface.
Dummyfs was written on 4.15, which btw is also outdated, and I need to update it to works with 5.2+ kernels as entire FS framework was changed.

You can take a look on yours header and verify `include/linux/fs.h`
I guess in your case that happening:
> Your kernel seems to have this interface
https://elixir.bootlin.com/linux/v4.4-rc1/source/include/linux/fs.h#L1607
>And 4.15 used have more methods
https://elixir.bootlin.com/linux/v4.15/source/include/linux/fs.h#L1700

So In theory you can just change `iterate_shared` to the old `iterate`.
The reason why I used newer interface over the old one was because it was newer and recommended for operations that do not update/modify dentry structure, thus potentially multiple processes can do operation in parallel. 
If you are interested more details please see the `iterate_dir` from `fs/readdir.c`
The whole `sharing` trick is done based on `inode` semaphore `i_rwsem`:

```
	if (shared)
		res = down_read_killable(&inode->i_rwsem);
	else
		res = down_write_killable(&inode->i_rwsem);
```
Please let me know if you have any other questions.
I plan to rewrite FS interface to be able to work with newer kernels, but need to manage some free time.
Hope above explanations will help.

**Comment by enogueiras** [comment]
Hi! thanks so much for your time answering, I tried change the following:

_const struct file_operations dummy_dir_ops = {
	.owner = THIS_MODULE,
        .iterate = dummy_readdir,
	// .iterate_shared = dummy_readdir,
};_

Now I dont get that error, but instead got the following error:

_utnso@ubuntu-server:~/workspace/dummyfs$ make
make -C /lib/modules/4.4.0-116-generic/build SUBDIRS=/home/utnso/workspace/dummyfs modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-116-generic'
  CC [M]  /home/utnso/workspace/dummyfs/dummyfs.o
  CC [M]  /home/utnso/workspace/dummyfs/super.o
/home/utnso/workspace/dummyfs/super.c: In function ‘dummyfs_fill_super’:
/home/utnso/workspace/dummyfs/super.c:48:24: error: implicit declaration of function ‘current_time’ [-Werror=implicit-function-declaration]
  root_inode->i_atime = current_time(root_inode);
                        ^
/home/utnso/workspace/dummyfs/super.c:48:22: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  root_inode->i_atime = current_time(root_inode);
                      ^
/home/utnso/workspace/dummyfs/super.c:49:22: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  root_inode->i_ctime = current_time(root_inode);
                      ^
/home/utnso/workspace/dummyfs/super.c:50:22: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  root_inode->i_mtime = current_time(root_inode);
                      ^
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/utnso/workspace/dummyfs/super.o' failed
make[2]: *** [/home/utnso/workspace/dummyfs/super.o] Error 1
Makefile:1423: recipe for target '_module_/home/utnso/workspace/dummyfs' failed
make[1]: *** [_module_/home/utnso/workspace/dummyfs] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-116-generic'
Makefile:16: recipe for target 'default' failed
make: *** [default] Error 2
utnso@ubuntu-server:~/workspace/dummyfs$_

I will be my old kernel again?

Thanks!

**Comment by mmpg-x86** [comment]
Correct that was another big change that you may read more on LKML, the function `current_time` was introduced to unify time and fix a couple of issues:

https://lkml.org/lkml/2016/1/7/20

Try to change a call to `current_time` to the `CURRENT_TIME_SEC` macro it should work, also make sure that CURRENT_TIME_SEC is visible in kernel headers.
As you can see in the conversation below, it was a significant change: https://www.redhat.com/archives/linux-audit/2016-June/msg00026.html

**Comment by mmpg-x86** [comment]
@enogueiras Any progress with compiling/running? 
Can I close the issue, or maybe you would be interested in writing #ifdef to make the code running on both versions?

```
#if LINUX_VERSION_CODE <= KERNEL_VERSION(4,4)
//use yourversion
#else
//use  newer version
#endif
```

**Comment by enogueiras** [comment]
Hi @gotoco  I made the suggested changes and I re did make, I got the following:

_utnso@ubuntu-server:~/workspace/practica_filesystem/dummyfs$ make
make -C /lib/modules/4.4.0-116-generic/build SUBDIRS=/home/utnso/workspace/practica_filesystem/dummyfs modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-116-generic'
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dummyfs.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/super.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/inode.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dir.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/file.o
In file included from include/linux/printk.h:6:0,
                 from include/linux/kernel.h:13,
                 from include/linux/uio.h:12,
                 from /home/utnso/workspace/practica_filesystem/dummyfs/file.c:1:
/home/utnso/workspace/practica_filesystem/dummyfs/file.c: In function ‘dummy_read’:
include/linux/kern_levels.h:4:18: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Wformat=]
 #define KERN_SOH "\001"  /* ASCII Start Of Header */
                  ^
include/linux/kern_levels.h:10:18: note: in expansion of macro ‘KERN_SOH’
 #define KERN_ERR KERN_SOH "3" /* error conditions */
                  ^
/home/utnso/workspace/practica_filesystem/dummyfs/file.c:54:17: note: in expansion of macro ‘KERN_ERR’
          printk(KERN_ERR "Failed to read data block %lu\n", blk);
                 ^
/home/utnso/workspace/practica_filesystem/dummyfs/file.c:39:9: warning: unused variable ‘end’ [-Wunused-variable]
  loff_t end = off + count;
         ^
In file included from include/linux/printk.h:6:0,
                 from include/linux/kernel.h:13,
                 from include/linux/uio.h:12,
                 from /home/utnso/workspace/practica_filesystem/dummyfs/file.c:1:
/home/utnso/workspace/practica_filesystem/dummyfs/file.c: In function ‘dummy_write’:
include/linux/kern_levels.h:4:18: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Wformat=]
 #define KERN_SOH "\001"  /* ASCII Start Of Header */
                  ^
include/linux/kern_levels.h:10:18: note: in expansion of macro ‘KERN_SOH’
 #define KERN_ERR KERN_SOH "3" /* error conditions */
                  ^
/home/utnso/workspace/practica_filesystem/dummyfs/file.c:113:13: note: in expansion of macro ‘KERN_ERR’
      printk(KERN_ERR "Failed to read data block %lu\n", blk);
             ^
  LD [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dmyfs.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/utnso/workspace/practica_filesystem/dummyfs/dmyfs.mod.o
  LD [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dmyfs.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-116-generic'_

Is that a correct state of compiling?

**Comment by enogueiras** [comment]
I made a few other changes (data types mostly) and I didn't get warnings now:

utnso@ubuntu-server:~/workspace/practica_filesystem/dummyfs$ make
make -C /lib/modules/4.4.0-116-generic/build SUBDIRS=/home/utnso/workspace/practica_filesystem/dummyfs modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-116-generic'
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dummyfs.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/super.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/inode.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dir.o
  CC [M]  /home/utnso/workspace/practica_filesystem/dummyfs/file.o
  LD [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dmyfs.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/utnso/workspace/practica_filesystem/dummyfs/dmyfs.mod.o
  LD [M]  /home/utnso/workspace/practica_filesystem/dummyfs/dmyfs.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-116-generic'
utnso@ubuntu-server:~/workspace/practica_filesystem/dummyfs$

**Comment by enogueiras** [comment]
In step 2, I got the following

utnso@ubuntu-server:~/workspace/practica_filesystem/dummyfs$ gcc -o mkfs_dmfs mkfs_dummyfs.c -g
mkfs_dummyfs.c: In function ‘write_lostfound_inode’:
mkfs_dummyfs.c:258:2: warning: implicit declaration of function ‘syncfs’ [-Wimplicit-function-declaration]
  syncfs(fd);
  ^

I fixed with:

gcc -o mkfs_dmfs mkfs_dummyfs.c -g -D _GNU_SOURCE

:)

**Comment by mmpg-x86** [comment]
Well done! Happy that you solved by yourself!
